services:
  api.todolist.dev:
    platform: linux/amd64
    image: dev
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: api.todolist.dev
    ports:
      - 8888:8080
    restart: always